version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express_example
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user
 