version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user